from abc import ABC
from models.position import Position


class GameEventListener(ABC):
    """Subscriber interface. Implement any subset of methods to react to game events."""
    def on_move_applied(self, source: Position, target: Position): ...
    def on_king_captured(self, pos: Position): ...
    def on_pawn_promoted(self, pos: Position): ...
    def on_collision(self, pos: Position): ...
